### ISSUE TITLE
VM support on Mac

### ISSUE THREAD

**Issue by Xpirix** [imincik/nixos-server-deployment#7]
Hi @imincik,

Thanks for the Nix support on Mac. I am now able to run the `nix-develop` command.

Is it also possible to add this support for the VM?

When I run `nix run .#server1`, it returns the following error:

```
error: a 'x86_64-linux' with features {} is required to build '/nix/store/81nyr3i160n64vasls2cv4nqih6zg6zk-mounts.sh.drv', but I am a 'x86_64-darwin' with features {apple-virt, benchmark, big-parallel, nixos-test}
```

Is this related to this line?

https://github.com/imincik/nixos-server-deployment/blob/65e95d3a86ac974475fb7e6552b7d9ee20401ce8/hosts/server1/hardware.nix#L58

Thanks

**Comment by imincik** [comment]
You might need to set up a [linux-builder](https://nixcademy.com/posts/macos-linux-builder/) for that. See also https://nixcademy.com/posts/running-nixos-integration-tests-on-macos/
